//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MovieFinder.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class MovieLink
    {
        public int ID { get; set; }
        public int MovieID { get; set; }
        public string SiteTitle { get; set; }
        public string DownloadSiteID { get; set; }
        public string PageUrl { get; set; }
        public string PageSiteID { get; set; }
        public string DowloadUrl { get; set; }
        public string LinkTitle { get; set; }
        public int FailedAttempts { get; set; }
        public Nullable<System.DateTime> LastValidatedWhen { get; set; }
        public int Version { get; set; }
        public Nullable<System.Guid> LastValidatedBy { get; set; }
        public bool HasSubtitle { get; set; }
    
        public virtual Movie Movie { get; set; }
    }
}
