//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MovieFinder.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Plugin
    {
        public string GKName { get; set; }
        public string PluginName { get; set; }
        public string SiteID { get; set; }
        public int LastUpdatedTime { get; set; }
    }
}
